import Navbar from "./navbar/Navbar";
import Hero from "./hero/Hero";
import Release from "./Release/index";
import Genre from "./Genre";
import Footer from "./Footer";
import LoadingScreen from "./LoadingScreen";
import Table from "./table";
import Slider from "./Slider";
import ListAnime from "./Release/ListAnime";
import Star from "./childComponent/star";
import SliderCoverflow from "./Slider/SliderCoverflow";
import Episode from "./childComponent/Episode";
import SlinderRecomend from "./Slider/SlinderRecomend";
export { Star, Navbar, SlinderRecomend, SliderCoverflow, Episode, Hero, Release, Genre, Footer, LoadingScreen, Table, Slider, ListAnime };
